### ISSUE TITLE
Notify participants on new survey completions

### ISSUE THREAD

**Issue by ezl** [ezl/howdistant-backend#1]
If AAA completes a survey and invites BBB, currently AAA has no way to know that BBB has finished.

After AAA invites BBB, ask "Would you like to be notified when other people respond?" -> "Enter your email/phone #".

Then when BBB/CCC/DDD anyone completes the survey, notify that person "CCC also responded. check the group results here _____"

**Comment by shchoi22** [comment]
https://www.figma.com/file/mKn7r58iVL5sQ28J5cOEhT?node-id=1144:740#41808529
https://www.figma.com/file/mKn7r58iVL5sQ28J5cOEhT?node-id=1156:178#41808547

**Comment by shchoi22** [comment]
@ezl Do you have a Twilio account already setup for side projects or should be just create a new project under Rentapp account?

**Comment by ezl** [comment]
@shchoi22 I invited you to the twilio account that was created for SIP -- it has ~$100 in credits there
